### ISSUE TITLE
Sleep Diary Questions fix or change text 

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#19]
**Questions fix or change text **

Sleep Diary: 

**1.** Change Question 3 of 13 to : "What did you do the hour before GETTING into bed?"

**2.** Change Question 5 of 13 to: "When you got into bed, what did you do to try to go to sleep?"

**3.** Delete question 7 of 13

**4.** Change Question 8 of 13: If you had difficulty falling asleep, tap the boxes to specify why: 
o	Pain
o	Noise
o	Worries
o	I had no problems
o	Other _________
(Melanie: I will make buttons for it) 

**5.** Change Question 12 of 13 to: Did you take any medications before sleeping?

**Comment by alexlaurence** [comment]
Hi Melanie, let me know what you think: for points 3 and 4, I anticipate that at this stage it will take half the day to go through the code and cross reference what should change or not when adding/removing entire questions. So what I advise is for the app to skip the question entirely (rather than me physically removing it and updating all the codes). So as far as you're concerned as a researcher, in the database, that 'removed' column will just have blank entries. When exporting to excel, you can just delete that column/question manually yourself (in this case it will be question 7 of 13 in the sleep diary). I think that should make life a lot more easier for both of us... But let me know what you think!

**Comment by MK3112** [comment]
No problem at all.

Whatever is easier for you :)
