### ISSUE TITLE
Android: Back button PreLim for Qs 10 of 26

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#57]
**Android: Back button PreLim for Qs 10 of 25**
Back button on Qs 10 of 26 jumps back to 8 of 26 (see screenshot)

**To Reproduce**
1. Go to 'Register'
2. Do PreLim Questions
3. See error: Back button on Qs 10 of 26 jumps back to 8 of 26 (see screenshot)

**Expected behavior**
Should jump back to Qs 7 of 26 (Profession of parents) 

**Screenshots**
![whatsapp image 2018-07-23 at 18 59 13](https://user-images.githubusercontent.com/41471766/43094394-a440fcc8-8eaa-11e8-9c09-3fcca38bc4d8.jpeg)

**Smartphone (please complete the following information):**
 - Huawei: EMUI 5.0.1

**Comment by alexlaurence** [comment]
Ahh yeah, so I had a look and that was the right question - it's just the numbering that is wrong. The numbers have misaligned because you asked me to remove a question/add a question I think :) Since there was 26 of them, I had to change the text in all 26 scenes... 

At some point I'll fix the numbering, but it's a big task with over 100 scenes at the moment. You can help me, I'll teach you how!

**Comment by MK3112** [comment]
Oh I am very sorry! Yes please teach me so we can make it easier. What do I need to do?
