### ISSUE TITLE
Android: Question:Time Picker 

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#61]
First of all, great time picker ;) 

For question 6 of 13 "How long did it take you to fall asleep?" 
Do you think it might be a bit confusing to have am/pm in the time picker ? 

Same accounts for Qs 10 of 13 "How long did it take you to get out of bed in the morning" 

Since you need to indicate hours and minutes only? 
Maybe we can wait and see what others say :)

**Comment by alexlaurence** [comment]
Ahh, I'll wait what the others say! Because I have no idea, Melanie. The time picker brings up Android's native time picker for their OS version. Every phone will be unique to their usual standard... Mine shows a little clock face for example. 

iOS has a great native time picker (that dialer)... but I can't actually bring that over to Android since that's hard-coded into Apple's iOS system.

**Comment by MK3112** [comment]
No problem ;) we just wait and see what others say before we decide on that. Maybe it doesn’t even matter haha

Melanie Koelbel, PhD student

Developmental Neurosciences Programme
UCL Great Ormond Street Institute of Child Health
30 Guilford Street | London | WC1N 1EH

________________________________
